server:
  port: 8201

spring:
  application:
    name: vmmgmt-service

eureka:
  instance:
    instance-id: vmmgmt-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka