server:
  port: 8401

spring:
  application:
    name: agentmgmt-service

eureka:
  instance:
    instance-id: agentmgmt-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
