server:
  port: 8301

spring:
  application:
    name: network-service

eureka:
  instance:
    instance-id: network-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka