server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: token-service
          uri: lb://TOKEN-SERVICE
          predicates:
            - Path=/token/**

        - id: vmmgmt-service
          uri: lb://VMMGMT-SERVICE
          predicates:
            - Path=/mqsvr/**

        - id: network-service
          uri: lb://NETWORK-SERVICE
          predicates:
            - Path=/net/**

        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web/**

        - id: agentmgmt-service
          uri: lb://AGENTMGMT-SERVICE
          predicates:
            - Path=/agentmgmt/**