server:
  port: 8101

spring:
  application:
    name: token-service

eureka:
  instance:
    instance-id: token-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka